
import { NAV_ITEMS, calculateStats, clone, composeFullText, isOverdue, normalizeData, normalizeNote, normalizePublishLog, productIdForName, shootKey, todayShanghai, toNullableNumber } from "./v2-model.js";

const root = document.querySelector("#app");
const S = { view: "today", date: todayShanghai(), data: null, revision: 0, selected: "", dialog: null, error: "", toast: "", saving: false };
const metrics = [["exposure","曝光"],["views","观看"],["ctr","CTR"],["likes","点赞"],["saves","收藏"],["comments","评论"],["follows","涨粉"]];
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;" }[c]));
const at = (v) => esc(v);
const words = () => S.data.emotionWords.filter((w) => !w.archived);
const word = (id) => S.data.emotionWords.find((w) => w.id === id);
const caption = (w, id) => w?.captions.find((c) => c.id === id);
const id = (p) => p + "-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 6);
const num = (v) => v === null || v === undefined ? "—" : new Intl.NumberFormat("zh-CN", { maximumFractionDigits: 1 }).format(v);

async function api(path, options = {}) {
  const response = await fetch(path, { credentials: "same-origin", ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (response.status === 401) { window.location.href = "/login.html?next=" + encodeURIComponent(location.pathname); throw new Error("登录已过期。"); }
  if (!response.ok) { const e = new Error(data.message || "请求失败。"); e.status = response.status; e.data = data; throw e; }
  return data;
}
async function load() {
  try { const result = await api("/api/v2-workspace"); S.data = normalizeData(result.data); S.revision = result.revision; S.selected = words()[0]?.id || ""; render(); }
  catch (e) { S.error = e.message; render(); }
}
async function save(next, message = "已保存") {
  S.saving = true; render();
  try { const result = await api("/api/v2-workspace", { method: "POST", body: JSON.stringify({ expectedRevision: S.revision, data: next }) }); S.data = normalizeData(result.data); S.revision = result.revision; S.toast = message; S.error = ""; }
  catch (e) { if (e.status === 409 && e.data?.current) { S.data = normalizeData(e.data.current.data); S.revision = e.data.current.revision; S.error = "数据已更新，当前页面已刷新，请重新提交操作。"; } else S.error = e.message; }
  finally { S.saving = false; render(); }
}
function mutate(fn, message) { const next = clone(S.data); fn(next); return save(next, message); }
function render() {
  if (!S.data) { root.innerHTML = S.error ? `<div class="error-screen"><div class="error-card"><p class="eyebrow">V2 工作台</p><h1>连接 Neon V2 失败</h1><p>${esc(S.error)}</p><button class="button primary" data-retry>重试</button></div></div>` : `<div class="boot"><span class="spinner"></span><p>正在打开情绪词日记…</p></div>`; bind(); return; }
  const current = NAV_ITEMS.find((n) => n[0] === S.view) || NAV_ITEMS[0];
  root.innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">清</span><div><strong>清熙小院</strong><small>情绪词日记</small></div></div><div class="sidebar-date"><span>上海日期</span><b>${todayShanghai()}</b></div><nav class="nav">${NAV_ITEMS.map(([key,label,no]) => `<button class="nav-item ${S.view === key ? "active" : ""}" data-nav="${key}"><span>${no}</span>${label}</button>`).join("")}</nav><div class="sidebar-foot"><span class="status-dot"></span>${S.saving ? "保存中…" : "V2 · rev " + S.revision}<button class="icon-button" data-logout>↗</button></div></aside><main id="main-content" class="main"><header class="topbar"><div><p class="eyebrow">清熙小院 / V2 WORKSPACE</p><h1>${current[1]}</h1></div><div class="top-actions"><button class="button subtle" data-export>导出 JSON</button><label class="button subtle file-button">恢复 JSON<input type="file" accept="application/json" data-import hidden /></label></div></header>${S.toast ? `<div class="toast" role="status">${esc(S.toast)}</div>` : ""}${S.error ? `<div class="inline-error" role="alert">${esc(S.error)}<button data-dismiss>知道了</button></div>` : ""}<div class="view-content">${viewMarkup()}</div></main><nav class="mobile-nav">${NAV_ITEMS.map(([key,label,no]) => `<button class="${S.view === key ? "active" : ""}" data-nav="${key}"><span>${no}</span><small>${label}</small></button>`).join("")}</nav></div><div id="dialog-root">${dialogMarkup()}</div>`;
  bind();
}
function viewMarkup() { return ({ today: todayView, words: wordsView, logs: logsView, shoot: shootView, notes: notesView, resources: resourcesView }[S.view] || todayView)(); }
function stat(label, value, note) { return `<div class="stat"><span>${label}</span><strong>${num(value)}</strong><small>${note}</small></div>`; }
function todayView() {
  const today = todayShanghai(), stats = calculateStats(S.data.publishLog), selected = word(S.selected) || words()[0], used = new Set(S.data.publishLog.filter((e) => e.wordId === selected?.id).map((e) => e.captionId)), next = selected?.captions.find((c) => !c.archived && !used.has(c.id)) || selected?.captions.find((c) => !c.archived), notes = S.data.scheduledNotes.filter((n) => n.date === today && n.status === "scheduled");
  return `<section class="hero-grid"><div class="hero-panel"><p class="eyebrow">${today} · 今日只做一件事</p><h2>把一个情绪，写成<br><em>值得保存的下午。</em></h2><p class="hero-copy">从词库挑一个状态，拿上拍摄清单，三次点击完成发布登记。</p><div class="hero-meta"><span class="status-dot"></span>${S.data.publishLog.filter((e) => e.date === today).length ? "今天已登记发布" : "今天还没有发布记录"}<span class="divider"></span>连续 ${stats.streak} 天</div></div><div class="today-card"><div class="section-kicker">今日排期 <span>${notes.length || "暂无"}</span></div>${notes.length ? notes.map((n) => `<div class="schedule-line"><b>${esc(n.title)}</b><small>${esc(n.body)}</small></div>`).join("") : `<p class="empty-copy">今天没有固定排期。<button class="text-button" data-nav="notes">去写一条 →</button></p>`}</div></section><section class="stat-strip">${stat("发布次数",stats.count,"全部日志")}${stat("平均观看",stats.avgViews,"空值不计")}${stat("平均点赞",stats.avgLikes,"空值不计")}${stat("本周发布",stats.weekCount,"近 7 天")}${stat("合计涨粉",stats.follows,"0 也有效")}</section><section class="section-heading"><div><p class="eyebrow">12 个入口</p><h2>今天想写哪种心情</h2></div><button class="text-button" data-nav="words">管理词库 →</button></section><div class="word-grid">${words().map(wordCard).join("")}</div>${selected ? focusView(selected,next,used) : `<div class="empty-state">还没有情绪词，请先新增。</div>`}`;
}
function wordCard(w) { const logs = S.data.publishLog.filter((e) => e.wordId === w.id), usable = w.captions.filter((c) => !c.archived), recent = logs.map((e) => e.date).sort().at(-1) || "尚未使用"; return `<button class="word-card ${S.selected === w.id ? "selected" : ""}" data-select="${at(w.id)}"><span class="word-index">${esc(w.groupLabel)}</span><strong>${esc(w.name)}</strong><span class="word-foot"><small>${logs.length}/${usable.length} 已用</small><small>${recent}</small></span></button>`; }
function focusView(w, next, used) { const checks = S.data.dailyShootChecks[todayShanghai()] || {}; return `<section class="focus-panel"><div class="focus-main"><div class="section-kicker">${esc(w.groupLabel)} · ${w.weatherDependent ? "看天气" : "随时可用"}</div><h2>${esc(w.name)}</h2><p>${esc(w.copyDirection || "从今天的一个细节开始，写下它。")}</p><div class="tag-row">${w.extraTags.map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div><div class="focus-actions"><button class="button primary" data-publish="${at(w.id)}" data-caption="${at(next?.id || "")}" ${next ? "" : "disabled"}>登记今天发布</button><button class="button secondary" data-copy="${at(w.id)}" data-caption="${at(next?.id || "")}" ${next ? "" : "disabled"}>复制完整文本</button></div></div><aside class="focus-side"><p class="eyebrow">拍摄提示</p><ul class="compact-list">${w.shootList.map((x,i) => `<li><span>${i+1}</span>${esc(x)}</li>`).join("")}</ul><p class="side-note">${used.size ? "优先未用文案，已用文案仍可复用。" : "这是这个情绪词的第一条候选文案。"}</p></aside></section><section class="section-heading"><div><p class="eyebrow">候选文案 · ${w.captions.filter((c) => !c.archived).length} 条</p><h2>${esc(w.name)} 的写法</h2></div></section><div class="caption-list">${w.captions.filter((c) => !c.archived).map((c) => `<article class="caption-card ${used.has(c.id) ? "is-used" : ""}"><div class="caption-top"><span class="caption-id">${used.has(c.id) ? "已用" : "未用优先"}</span><h3>${esc(c.title)}</h3></div><p>${esc(c.body)}</p><div class="caption-actions"><button class="text-button" data-copy="${at(w.id)}" data-caption="${at(c.id)}">复制完整文本</button><button class="text-button" data-publish="${at(w.id)}" data-caption="${at(c.id)}">登记发布</button></div></article>`).join("")}</div>`; }
function wordsView() { return `<section class="manage-grid"><div class="panel"><div class="section-heading tight"><div><p class="eyebrow">词库设置</p><h2>保持入口新鲜</h2></div><button class="button primary" data-edit-word="">新增情绪词</button></div><form data-form="settings" class="stack-form"><label>固定结尾<textarea name="fixedFooter" rows="4">${esc(S.data.emotionSettings.fixedFooter)}</textarea></label><label>基础标签<input name="baseTags" value="${at(S.data.emotionSettings.baseTags.join(" "))}" placeholder="#成都周末去哪 #新津" /></label><button class="button secondary">保存词库设置</button></form></div><div class="panel"><p class="eyebrow">编辑规则</p><h2>可复用，但不覆盖</h2><p class="panel-copy">文案归档后仍保留，发布日志保存实际标题、正文、标签和完整文本。</p><div class="rule-list"><div><b>稳定 ID</b><span>词、文案、产品都用 ID 关联</span></div><div><b>上海日期</b><span>拍摄状态按 Asia/Shanghai 保存</span></div><div><b>空值</b><span>未填为 null，0 会参与统计</span></div></div></div></section><section class="section-heading"><div><p class="eyebrow">情绪词</p><h2>12 个内容入口</h2></div></section><div class="admin-word-list">${S.data.emotionWords.map((w) => `<article class="admin-word ${w.archived ? "archived" : ""}"><div><span class="eyebrow">${esc(w.groupLabel)} · ${w.id}</span><h3>${esc(w.name)}</h3><p>${esc(w.copyDirection || "未填写写作方向")}</p><div class="tag-row">${w.productIds.map((p) => `<span class="tag muted">${esc(S.data.products.find((x) => x.id === p)?.name || p)}</span>`).join("")}</div></div><div class="admin-actions"><span class="count-label">${w.captions.filter((c) => !c.archived).length} 条可用</span><button class="text-button" data-edit-word="${at(w.id)}">编辑</button><button class="text-button" data-archive-word="${at(w.id)}">${w.archived ? "恢复" : "归档"}</button><button class="text-button" data-captions="${at(w.id)}">编辑文案</button></div></article>`).join("")}</div>`; }
function logsView() { const s = calculateStats(S.data.publishLog); return `<section class="stat-strip log-stats">${stat("发布次数",s.count,"不可变快照")}${stat("平均观看",s.avgViews,"空值不计")}${stat("平均点赞",s.avgLikes,"空值不计")}${stat("平均收藏",s.avgSaves,"空值不计")}${stat("样本数量",s.samples,"已有记录")}${stat("连续发布",s.streak,"天")}</section><div class="log-list">${S.data.publishLog.length ? [...S.data.publishLog].sort((a,b) => b.date.localeCompare(a.date)).map(logCard).join("") : `<div class="empty-state"><h3>还没有发布日志</h3><p>从今日发布登记一条，就会生成快照。</p></div>`}</div>`; }
function logCard(e) { return `<article class="log-card"><div class="log-date"><strong>${esc(e.date)}</strong><span>${esc(e.wordNameSnapshot)}</span></div><div class="log-content"><h3>${esc(e.publishedTitle)}</h3><p>${esc(e.publishedBody)}</p><div class="tag-row">${e.publishedTags.map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div><details><summary>查看完整发布快照</summary><pre>${esc(e.fullTextSnapshot)}</pre></details></div><div class="log-side"><span class="snapshot-badge">SNAPSHOT</span>${metrics.slice(1,4).map(([k,l]) => `<div class="metric-mini"><b>${num(e.metrics[k])}</b><small>${l}</small></div>`).join("")}<button class="text-button" data-log="${at(e.id)}">补填数据</button></div></article>`; }
function shootView() { const day = todayShanghai(), checks = S.data.dailyShootChecks[day] || {}, total = words().reduce((n,w) => n+w.shootList.length,0), done = words().reduce((n,w) => n+w.shootList.filter((_,i) => checks[shootKey(w.id,i)]).length,0); return `<section class="hero-grid compact-hero"><div class="hero-panel"><p class="eyebrow">${day} · MOBILE FIRST</p><h2>拍摄前，<em>先把眼前的细节拍下来。</em></h2><p class="hero-copy">明天打开会按上海日期自然回到空白。</p><div class="progress-line"><span style="width:${total ? done/total*100 : 0}%"></span></div><div class="hero-meta">${done} / ${total} 已完成</div></div><div class="today-card"><div class="section-kicker">拍摄原则</div><p class="panel-copy">不上传照片，只记录今天要拍什么。</p></div></section><div class="shoot-list">${words().map((w) => `<section class="shoot-group"><div class="shoot-group-head"><div><span class="eyebrow">${esc(w.groupLabel)}</span><h3>${esc(w.name)}</h3></div><span class="count-label">${w.shootList.filter((_,i) => checks[shootKey(w.id,i)]).length}/${w.shootList.length}</span></div><div class="check-list">${w.shootList.map((x,i) => { const k=shootKey(w.id,i); return `<label class="check-item ${checks[k] ? "done" : ""}"><input type="checkbox" data-shoot="${at(k)}" ${checks[k] ? "checked" : ""}/><span class="check-mark"></span><span>${esc(x)}</span></label>`; }).join("")}</div></section>`).join("")}</div>`; }
function notesView() { const today = todayShanghai(), list = [...S.data.scheduledNotes].sort((a,b) => a.date.localeCompare(b.date)); return `<section class="section-heading"><div><p class="eyebrow">排期笔记</p><h2>把想发的日子写下来</h2><p class="section-copy">同一天可以多条，逾期会标红提醒。</p></div><button class="button primary" data-note="">新增排期</button></section><div class="notes-list">${list.length ? list.map((n) => `<article class="note-card ${isOverdue(n,today) ? "overdue" : ""}"><div class="note-date"><strong>${esc(n.date)}</strong><span>${n.status === "cancelled" ? "已取消" : n.status === "published" ? "已发布" : isOverdue(n,today) ? "已逾期" : "待发布"}</span></div><div class="note-body"><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></div><div class="admin-actions"><button class="text-button" data-note="${at(n.id)}">编辑</button><button class="text-button danger-text" data-delete-note="${at(n.id)}">删除</button></div></article>`).join("") : `<div class="empty-state"><h3>还没有排期笔记</h3><p>先记录一个具体日期和想捕捉的情绪。</p></div>`}</div>`; }
function resourcesView() { return `<section class="section-heading"><div><p class="eyebrow">产品 / 资料</p><h2>让关联回到稳定 ID</h2></div><div class="top-actions"><button class="button secondary" data-product="">新增产品</button><button class="button secondary" data-library="">新增资料</button></div></section><section class="resource-grid"><div class="panel"><div class="section-heading tight"><h3>产品</h3><span class="count-label">${S.data.products.length} 个</span></div>${S.data.products.map((p) => `<article class="resource-item ${p.archived ? "archived" : ""}"><div><b>${esc(p.name)}</b><small>${esc(p.category)} · ${esc(p.id)}</small><p>${esc(p.note || "暂无备注")}</p></div><button class="text-button" data-product="${at(p.id)}">编辑</button></article>`).join("")}</div><div class="panel"><div class="section-heading tight"><h3>资料</h3><span class="count-label">${S.data.library.length} 条</span></div>${S.data.library.map((x) => `<article class="resource-item ${x.archived ? "archived" : ""}"><div><b>${esc(x.title)}</b><small>${esc(x.id)}</small><p>${esc(x.note || x.url)}</p></div><button class="text-button" data-library="${at(x.id)}">编辑</button></article>`).join("") || `<p class="empty-copy">资料库还是空的。</p>`}</div></section>`; }
function open(type, payload = {}) { S.dialog = { type, payload }; render(); }
function dialogMarkup() {
  if (!S.dialog) return "";
  const { type, payload } = S.dialog;
  if (type === "publish") { const w=word(payload.wordId), c=caption(w,payload.captionId); return `<dialog open class="dialog"><form data-form="publish" data-word="${at(w?.id)}" data-caption="${at(c?.id)}"><div class="dialog-head"><div><p class="eyebrow">发布登记 · 快照将保留</p><h2>${esc(w?.name)}</h2></div><button class="close-button" data-close>×</button></div><div class="dialog-grid"><label>日期<input name="date" type="date" value="${todayShanghai()}" required/></label><label>标题<input name="title" maxlength="20" value="${at(c?.title)}" required/></label></div><label>正文<textarea name="body" rows="7" required>${esc(c?.body)}</textarea><label>标签<input name="tags" value="${at([...S.data.emotionSettings.baseTags,...(w?.extraTags||[])].join(" "))}"/></label><div class="dialog-grid"><label>笔记链接<input name="noteUrl" type="url"/></label><label>备注<input name="remark"/></label></div><div class="dialog-actions"><button class="button subtle" data-close>取消</button><button class="button primary">保存发布快照</button></div></form></dialog>`; }
  if (type === "word") { const w=payload.id ? word(payload.id) : {id:"",name:"",groupLabel:"场景情绪",shootList:[],extraTags:[],copyDirection:"",productIds:[],captions:[]}; return `<dialog open class="dialog"><form data-form="word" data-id="${at(w.id)}"><div class="dialog-head"><div><p class="eyebrow">词库管理</p><h2>${w.id ? "编辑情绪词" : "新增情绪词"}</h2></div><button class="close-button" data-close>×</button></div><div class="dialog-grid"><label>名称<input name="name" value="${at(w.name)}" required/></label><label>分组<input name="groupLabel" value="${at(w.groupLabel)}"/></label></div><label>拍摄清单<textarea name="shootList" rows="4">${esc(w.shootList.join("\\n"))}</textarea><label>额外标签<input name="extraTags" value="${at(w.extraTags.join(" "))}"/></label><label>写作方向<textarea name="copyDirection" rows="3">${esc(w.copyDirection)}</textarea><fieldset><legend>关联产品</legend><div class="product-checks">${S.data.products.map((p) => `<label><input type="checkbox" name="productIds" value="${at(p.id)}" ${w.productIds.includes(p.id) ? "checked" : ""}/>${esc(p.name)}</label>`).join("")}</div></fieldset><div class="dialog-actions"><button class="button subtle" data-close>取消</button><button class="button primary">保存情绪词</button></div></form></dialog>`; }
  if (type === "caption") { const w=word(payload.wordId), c=payload.id ? caption(w,payload.id) : {id:"",title:"",body:"",archived:false}; return `<dialog open class="dialog"><form data-form="caption" data-word="${at(w?.id)}" data-id="${at(c?.id)}"><div class="dialog-head"><div><p class="eyebrow">${esc(w?.name)} · 文案</p><h2>${c.id ? "编辑文案" : "新增文案"}</h2></div><button class="close-button" data-close>×</button></div><label>标题（≤20字）<input name="title" maxlength="20" value="${at(c.title)}" required/></label><label>正文<textarea name="body" rows="8" required>${esc(c.body)}</textarea><label class="toggle-line"><input type="checkbox" name="archived" ${c.archived ? "checked" : ""}/>归档此文案</label><div class="dialog-actions"><button class="button subtle" data-close>取消</button><button class="button primary">保存文案</button></div></form></dialog>`; }
  if (type === "captions") { const w=word(payload.wordId); return `<dialog open class="dialog wide"><div class="dialog-head"><div><p class="eyebrow">文案管理</p><h2>${esc(w?.name)}</h2></div><button class="close-button" data-close>×</button></div><div class="caption-admin-list">${w?.captions.map((c) => `<div class="caption-admin-row ${c.archived ? "archived" : ""}"><div><b>${esc(c.title)}</b><small>${c.archived ? "已归档" : c.id}</small></div><button class="text-button" data-caption-edit="${at(w.id)}" data-id="${at(c.id)}">编辑</button></div>`).join("")}<button class="button primary full-button" data-caption-add="${at(w?.id)}">新增文案</button></div></dialog>`; }
  if (type === "log") { const e=S.data.publishLog.find((x) => x.id === payload.id); return `<dialog open class="dialog"><form data-form="log" data-id="${at(e?.id)}"><div class="dialog-head"><div><p class="eyebrow">补填数据 · ${esc(e?.date)}</p><h2>${esc(e?.publishedTitle)}</h2></div><button class="close-button" data-close>×</button></div><div class="metric-grid">${metrics.map(([k,l]) => `<label>${l}<input name="${k}" type="number" step="any" value="${e?.metrics[k] ?? ""}/></label>`).join("")}</div><div class="dialog-grid"><label>笔记链接<input name="noteUrl" value="${at(e?.noteUrl)}"/></label><label>备注<input name="remark" value="${at(e?.remark)}"/></label></div><div class="dialog-actions"><button class="button subtle" data-close>取消</button><button class="button primary">保存补填</button></div></form></dialog>`; }
  if (type === "note") { const n=payload.id ? S.data.scheduledNotes.find((x) => x.id === payload.id) : {id:"",date:S.date,title:"",body:"",status:"scheduled",publishLogId:""}; return `<dialog open class="dialog"><form data-form="note" data-id="${at(n.id)}"><div class="dialog-head"><div><p class="eyebrow">排期笔记</p><h2>${n.id ? "编辑排期" : "新增排期"}</h2></div><button class="close-button" data-close>×</button></div><div class="dialog-grid"><label>日期<input name="date" type="date" value="${at(n.date)}" required/></label><label>状态<select name="status"><option value="scheduled" ${n.status==="scheduled"?"selected":""}>待发布</option><option value="published" ${n.status==="published"?"selected":""}>已发布</option><option value="cancelled" ${n.status==="cancelled"?"selected":""}>已取消</option></select></label></div><label>标题<input name="title" value="${at(n.title)}" required/></label><label>内容<textarea name="body" rows="5">${esc(n.body)}</textarea><div class="dialog-actions"><button class="button subtle" data-close>取消</button><button class="button primary">保存排期</button></div></form></dialog>`; }
  if (type === "product" || type === "library") { const p=type==="product", old=p ? S.data.products.find((x)=>x.id===payload.id) || {id:"",name:"",category:"茶饮",note:"",archived:false} : S.data.library.find((x)=>x.id===payload.id) || {id:"",title:"",url:"",note:"",archived:false}; return `<dialog open class="dialog"><form data-form="${type}" data-id="${at(old.id)}"><div class="dialog-head"><div><p class="eyebrow">产品 / 资料</p><h2>${old.id ? "编辑" : "新增"}${p ? "产品" : "资料"}</h2></div><button class="close-button" data-close>×</button></div><label>${p ? "名称" : "标题"}<input name="${p ? "name" : "title"} value="${at(p ? old.name : old.title)}" required/></label>${p ? `<div class="dialog-grid"><label>分类<input name="category" value="${at(old.category)}"/></label><label>稳定 ID<input name="id" value="${at(old.id)}" ${old.id ? "readonly" : ""}/></label></div>` : `<label>链接<input name="url" value="${at(old.url)}"/></label>`}<label>备注<textarea name="note" rows="3">${esc(old.note)}</textarea><label class="toggle-line"><input type="checkbox" name="archived" ${old.archived?"checked":""}/>归档</label><div class="dialog-actions"><button class="button subtle" data-close>取消</button><button class="button primary">保存</button></div></form></dialog>`; }
  return "";
}
function bind() {
  document.querySelectorAll("[data-nav]").forEach((b) => b.addEventListener("click", () => { S.view = b.dataset.nav; S.toast = ""; render(); }));
  document.querySelector("[data-retry]")?.addEventListener("click", load);
  document.querySelector("[data-dismiss]")?.addEventListener("click", () => { S.error = ""; render(); });
  document.querySelector("[data-export]")?.addEventListener("click", exportData);
  document.querySelector("[data-import]")?.addEventListener("change", importData);
  document.querySelector("[data-logout]")?.addEventListener("click", async () => { await fetch("/api/auth-logout", { method: "POST", credentials: "same-origin" }); location.href = "/login.html"; });
  document.querySelectorAll("[data-select]").forEach((b) => b.addEventListener("click", () => { S.selected = b.dataset.select; render(); }));
  document.querySelectorAll("[data-copy]").forEach((b) => b.addEventListener("click", () => copy(b.dataset.copy, b.dataset.caption)));
  document.querySelectorAll("[data-publish]").forEach((b) => b.addEventListener("click", () => open("publish", { wordId: b.dataset.publish, captionId: b.dataset.caption })));
  document.querySelectorAll("[data-edit-word]").forEach((b) => b.addEventListener("click", () => open("word", { id: b.dataset.editWord })));
  document.querySelectorAll("[data-archive-word]").forEach((b) => b.addEventListener("click", () => mutate((d) => { const w=d.emotionWords.find((x)=>x.id===b.dataset.archiveWord); if(w) w.archived=!w.archived; }, "词库状态已更新")));
  document.querySelectorAll("[data-captions]").forEach((b) => b.addEventListener("click", () => open("captions", { wordId: b.dataset.captions })));
  document.querySelectorAll("[data-caption-edit]").forEach((b) => b.addEventListener("click", () => open("caption", { wordId:b.dataset.captionEdit, id:b.dataset.id })));
  document.querySelector("[data-caption-add]")?.addEventListener("click", () => open("caption", { wordId: document.querySelector("[data-caption-add]").dataset.captionAdd }));
  document.querySelectorAll("[data-log]").forEach((b) => b.addEventListener("click", () => open("log", { id:b.dataset.log })));
  document.querySelectorAll("[data-note]").forEach((b) => b.addEventListener("click", () => open("note", { id:b.dataset.note })));
  document.querySelectorAll("[data-delete-note]").forEach((b) => b.addEventListener("click", () => mutate((d) => { d.scheduledNotes=d.scheduledNotes.filter((n)=>n.id!==b.dataset.deleteNote); }, "排期已删除")));
  document.querySelectorAll("[data-shoot]").forEach((input) => input.addEventListener("change", () => mutate((d) => { const day=todayShanghai(); d.dailyShootChecks[day] = { ...(d.dailyShootChecks[day] || {}), [input.dataset.shoot]: input.checked }; }, "拍摄状态已保存")));
  document.querySelectorAll("[data-product]").forEach((b) => b.addEventListener("click", () => open("product", { id:b.dataset.product })));
  document.querySelectorAll("[data-library]").forEach((b) => b.addEventListener("click", () => open("library", { id:b.dataset.library })));
  document.querySelectorAll("[data-close]").forEach((b) => b.addEventListener("click", (e) => { e.preventDefault(); S.dialog=null; render(); }));
  document.querySelector(".dialog")?.addEventListener("click", (e) => { if (e.target.tagName === "DIALOG") { S.dialog=null; render(); } });
  document.querySelectorAll("form[data-form]").forEach((form) => form.addEventListener("submit", (e) => handleForm(e, form)));
}
async function handleForm(event, form) {
  event.preventDefault();
  const v = Object.fromEntries(new FormData(form).entries()), now = new Date().toISOString(), type = form.dataset.form;
  if (type === "settings") { await mutate((d) => { d.emotionSettings.fixedFooter=v.fixedFooter||""; d.emotionSettings.baseTags=String(v.baseTags||"").split(/[\\s,]+/).filter(Boolean); }, "词库设置已保存"); return; }
  if (type === "publish") {
    const w=word(form.dataset.word), c=caption(w,form.dataset.caption), tags=String(v.tags||"").split(/[\\s,]+/).filter(Boolean);
    const entry=normalizePublishLog({ id:id("publish"), date:v.date, wordId:w.id, captionId:c.id, wordNameSnapshot:w.name, publishedTitle:v.title, publishedBody:v.body, publishedTags:tags, fullTextSnapshot:composeFullText({ ...w, extraTags:tags.filter((x)=>!S.data.emotionSettings.baseTags.includes(x)) }, { body:v.body }, { fixedFooter:S.data.emotionSettings.fixedFooter, baseTags:[] }), noteUrl:v.noteUrl, remark:v.remark, metrics:{}, createdAt:now, updatedAt:now });
    await mutate((d)=>d.publishLog.unshift(entry),"发布快照已登记"); S.dialog=null; render(); return;
  }
  if (type === "word") {
    const old=form.dataset.id ? word(form.dataset.id) : null, productIds=Array.isArray(v.productIds)?v.productIds:(v.productIds?[v.productIds]:[]);
    const next={ id:old?.id||id("word"), name:v.name, group:old?.group||"custom", groupLabel:v.groupLabel||"其他", weatherDependent:false, shootList:String(v.shootList||"").split("\\n").map((x)=>x.trim()).filter(Boolean), copyDirection:v.copyDirection||"", seoReason:old?.seoReason||"", operationJudge:old?.operationJudge||"", extraTags:String(v.extraTags||"").split(/[\\s,]+/).filter(Boolean), productIds, archived:old?.archived||false, captions:old?.captions||[] };
    await mutate((d)=>{const i=d.emotionWords.findIndex((x)=>x.id===next.id); if(i>=0)d.emotionWords[i]=next; else d.emotionWords.push(next);},"情绪词已保存"); S.dialog=null; render(); return;
  }
  if (type === "caption") {
    const w=word(form.dataset.word), old=form.dataset.id ? caption(w,form.dataset.id) : null, next={id:old?.id||id("caption"),title:v.title,body:v.body,archived:v.archived==="on"};
    await mutate((d)=>{const x=d.emotionWords.find((z)=>z.id===w.id), i=x.captions.findIndex((z)=>z.id===next.id); if(i>=0)x.captions[i]=next; else x.captions.push(next);},"文案已保存"); S.dialog=null; render(); return;
  }
  if (type === "log") {
    await mutate((d)=>{const e=d.publishLog.find((x)=>x.id===form.dataset.id); if(!e)return; e.metrics=Object.fromEntries(metrics.map(([k])=>[k,toNullableNumber(v[k])])); e.noteUrl=v.noteUrl||""; e.remark=v.remark||""; e.updatedAt=now;},"发布数据已补填"); S.dialog=null; render(); return;
  }
  if (type === "note") {
    const old=form.dataset.id ? S.data.scheduledNotes.find((x)=>x.id===form.dataset.id) : null, next=normalizeNote({id:old?.id||id("note"),date:v.date,title:v.title,body:v.body,status:v.status,createdAt:old?.createdAt||now,updatedAt:now});
    await mutate((d)=>{const i=d.scheduledNotes.findIndex((x)=>x.id===next.id); if(i>=0)d.scheduledNotes[i]=next; else d.scheduledNotes.push(next);},"排期已保存"); S.dialog=null; render(); return;
  }
  if (type === "product") {
    const old=form.dataset.id ? S.data.products.find((x)=>x.id===form.dataset.id) : null, name=String(v.name||"").trim(), next={id:old?.id||v.id||productIdForName(name,S.data.products.length),name,category:v.category||"茶饮",note:v.note||"",archived:v.archived==="on"};
    await mutate((d)=>{const i=d.products.findIndex((x)=>x.id===next.id); if(i>=0)d.products[i]=next; else d.products.push(next);},"产品已保存"); S.dialog=null; render(); return;
  }
  if (type === "library") {
    const old=form.dataset.id ? S.data.library.find((x)=>x.id===form.dataset.id) : null, next={id:old?.id||id("library"),title:v.title,url:v.url||"",note:v.note||"",archived:v.archived==="on"};
    await mutate((d)=>{const i=d.library.findIndex((x)=>x.id===next.id); if(i>=0)d.library[i]=next; else d.library.push(next);},"资料已保存"); S.dialog=null; render();
  }
}
async function copy(wordId, captionId) {
  const w=word(wordId), c=caption(w,captionId); if(!w||!c)return;
  try { await navigator.clipboard.writeText(composeFullText(w,c,S.data.emotionSettings)); S.toast="完整发布文本已复制"; } catch { S.error="复制失败，请手动打开候选文案。"; }
  render();
}
function exportData() { const url=URL.createObjectURL(new Blob([JSON.stringify(S.data,null,2)],{type:"application/json"})), a=document.createElement("a"); a.href=url; a.download="qingxi-v2-"+todayShanghai()+".json"; a.click(); URL.revokeObjectURL(url); S.toast="V2 JSON 已导出"; render(); }
async function importData(e) { const file=e.target.files?.[0]; if(!file||!window.confirm("恢复会覆盖当前 V2 数据，是否继续？"))return; try { await save(normalizeData(JSON.parse(await file.text())),"V2 数据已恢复"); } catch(err) { S.error="恢复失败："+err.message; } e.target.value=""; render(); }
load();
