
const EMPTY = { schemaVersion: 1, emotionSettings: { fixedFooter: "", baseTags: [] }, emotionWords: [], publishLog: [], scheduledNotes: [], dailyShootChecks: {}, products: [], library: [] };
export const WORKSPACE_ID = "qingxi-v2";
export const NAV_ITEMS = [["today","今日发布","01"],["words","词库管理","02"],["logs","发布日志","03"],["shoot","拍摄清单","04"],["notes","排期笔记","05"],["resources","产品 / 资料","06"]];
export function productIdForName(name, index = 0) { const slug = Array.from(String(name || index + 1).trim()).map((char) => /[a-z0-9]/i.test(char) ? char.toLowerCase() : char.codePointAt(0).toString(16)).join("-"); return "product-" + (slug || index + 1); }
export function normalizePublishLog(entry = {}) { const metrics = entry.metrics && typeof entry.metrics === "object" ? entry.metrics : {}; return { id: String(entry.id || "publish-" + Date.now()), date: String(entry.date || ""), wordId: String(entry.wordId || ""), captionId: String(entry.captionId || ""), wordNameSnapshot: String(entry.wordNameSnapshot || ""), publishedTitle: String(entry.publishedTitle || ""), publishedBody: String(entry.publishedBody || ""), publishedTags: Array.isArray(entry.publishedTags) ? entry.publishedTags.map(String).filter(Boolean) : [], fullTextSnapshot: String(entry.fullTextSnapshot || ""), noteUrl: String(entry.noteUrl || ""), remark: String(entry.remark || ""), metrics: Object.fromEntries(["exposure","views","ctr","likes","saves","comments","follows"].map((key) => [key, metrics[key] === null || metrics[key] === undefined || metrics[key] === "" ? null : Number(metrics[key])]).filter(([, value]) => value === null || Number.isFinite(value))), createdAt: String(entry.createdAt || new Date().toISOString()), updatedAt: String(entry.updatedAt || entry.createdAt || new Date().toISOString()) }; }
export function normalizeNote(note = {}) { return { id: String(note.id || "note-" + Date.now()), date: String(note.date || ""), title: String(note.title || ""), body: String(note.body || ""), status: ["scheduled","published","cancelled"].includes(note.status) ? note.status : "scheduled", publishLogId: String(note.publishLogId || ""), createdAt: String(note.createdAt || new Date().toISOString()), updatedAt: String(note.updatedAt || note.createdAt || new Date().toISOString()) }; }
export function normalizeData(input = {}) {
  const source = input && typeof input === "object" ? input : {}, rawProducts = Array.isArray(source.products) ? source.products : [];
  const names = [...new Set([...rawProducts.map((p) => typeof p === "string" ? p : p?.name), ...(Array.isArray(source.emotionWords) ? source.emotionWords.flatMap((w) => Array.isArray(w?.products) ? w.products : []) : [])].filter(Boolean))];
  const ids = new Map(names.map((name, index) => [name, rawProducts.find((p) => (typeof p === "string" ? p : p?.name) === name)?.id || productIdForName(name, index)]));
  const products = names.map((name, index) => { const raw = rawProducts.find((p) => (typeof p === "string" ? p : p?.name) === name) || {}; return { id: raw.id || ids.get(name) || productIdForName(name, index), name, category: raw.category || raw.type || "茶饮", note: raw.note || "", archived: Boolean(raw.archived) }; });
  const words = (Array.isArray(source.emotionWords) ? source.emotionWords : []).map((word, wi) => ({ id: String(word?.id || "word-" + (wi + 1)), name: String(word?.name || "未命名情绪"), group: String(word?.group || "other"), groupLabel: String(word?.groupLabel || "其他"), weatherDependent: Boolean(word?.weatherDependent), shootList: Array.isArray(word?.shootList) ? word.shootList.map(String).filter(Boolean) : [], copyDirection: String(word?.copyDirection || ""), seoReason: String(word?.seoReason || ""), operationJudge: String(word?.operationJudge || ""), extraTags: Array.isArray(word?.extraTags) ? word.extraTags.map(String).filter(Boolean) : [], productIds: [...new Set(Array.isArray(word?.productIds) ? word.productIds.filter(Boolean) : (Array.isArray(word?.products) ? word.products : []).map((name, i) => ids.get(name) || productIdForName(name, i)))], archived: Boolean(word?.archived), captions: (Array.isArray(word?.captions) ? word.captions : []).map((caption, ci) => ({ id: String(caption?.id || "caption-" + (wi + 1) + "-" + (ci + 1)), title: String(caption?.title || ""), body: String(caption?.body || ""), archived: Boolean(caption?.archived) })) }));
  const settings = source.emotionSettings || {};
  return { ...EMPTY, emotionSettings: { fixedFooter: String(settings.fixedFooter ?? source.fixedFooter ?? ""), baseTags: Array.isArray(settings.baseTags) ? settings.baseTags.map(String).filter(Boolean) : (Array.isArray(source.baseTags) ? source.baseTags.map(String).filter(Boolean) : []) }, emotionWords: words, publishLog: Array.isArray(source.publishLog) ? source.publishLog.map(normalizePublishLog) : [], scheduledNotes: Array.isArray(source.scheduledNotes) ? source.scheduledNotes.map(normalizeNote) : [], dailyShootChecks: source.dailyShootChecks && typeof source.dailyShootChecks === "object" ? source.dailyShootChecks : {}, products, library: Array.isArray(source.library) ? source.library.map((item, i) => ({ id: item?.id || "library-" + (i + 1), title: String(item?.title || ""), url: String(item?.url || ""), note: String(item?.note || ""), archived: Boolean(item?.archived) })) : [] };
}
export function todayShanghai(date = new Date()) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).format(date); }
export function composeFullText(word, caption, settings = {}) { return [caption?.body || "", settings.fixedFooter || "", [...(settings.baseTags || []), ...(word?.extraTags || [])].filter(Boolean).join(" ")].filter(Boolean).join("\n\n").trim(); }
export function toNullableNumber(value) { if (value === null || value === undefined || String(value).trim() === "") return null; const number = Number(value); return Number.isFinite(number) ? number : null; }
export function calculateStats(log = [], now = new Date()) { const entries = log.map(normalizePublishLog), today = todayShanghai(now), day = new Date(today + "T00:00:00+08:00"), start = day.getTime() - 6 * 86400000; const avg = (key) => { const values = entries.map((e) => e.metrics[key]).filter((v) => Number.isFinite(v)); return values.length ? values.reduce((a, b) => a + b, 0) / values.length : null; }; const weekCount = entries.filter((e) => { const time = Date.parse(e.date + "T00:00:00+08:00"); return Number.isFinite(time) && time >= start && time <= day.getTime() + 86400000; }).length; const dates = new Set(entries.map((e) => e.date)), streak = (() => { let n = 0; for (let i = 0; i < 366; i++) { const d = new Date(day.getTime() - i * 86400000); const text = todayShanghai(d); if (!dates.has(text)) break; n++; } return n; })(); return { count: entries.length, avgViews: avg("views"), avgLikes: avg("likes"), avgSaves: avg("saves"), follows: entries.reduce((sum, e) => sum + (Number.isFinite(e.metrics.follows) ? e.metrics.follows : 0), 0), samples: entries.length, weekCount, streak }; }
export function shootKey(wordId, index) { return wordId + ":" + index; }
export function isOverdue(note, today = todayShanghai()) { return note?.status === "scheduled" && note?.date && note.date < today; }
export function clone(value) { return JSON.parse(JSON.stringify(value)); }
