
import { neon } from "@neondatabase/serverless";
import seed from "./_v2-seed.js";
import { normalizeData, WORKSPACE_ID } from "../src/v2-model.js";
export const TABLE_NAME = "qingxi_app_v2";
export function getDatabaseUrl() { return process.env.QINGXI_V2_DATABASE_URL || process.env.DATABASE_URL || process.env.POSTGRES_URL || ""; }
export function getSeedData() { return normalizeData(seed); }
export function assertDataShape(data) { if (!data || typeof data !== "object" || data.schemaVersion !== 1 || !Array.isArray(data.emotionWords) || !Array.isArray(data.publishLog) || !Array.isArray(data.scheduledNotes)) throw new Error("V2 数据结构不完整。"); return normalizeData(data); }
export async function ensureV2Table(sql) { await sql`CREATE TABLE IF NOT EXISTS qingxi_app_v2 (workspace_id TEXT PRIMARY KEY, data JSONB NOT NULL, revision INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`; }
export async function loadOrSeedV2() { const url = getDatabaseUrl(); if (!url) throw new Error("服务端未设置 V2 Neon 连接变量。"); const sql = neon(url); await ensureV2Table(sql); await sql`INSERT INTO qingxi_app_v2 (workspace_id, data, revision) VALUES (\${WORKSPACE_ID}, \${JSON.stringify(getSeedData())}::jsonb, 0) ON CONFLICT (workspace_id) DO NOTHING`; const rows = await sql`SELECT workspace_id, data, revision, created_at, updated_at FROM qingxi_app_v2 WHERE workspace_id = \${WORKSPACE_ID}`; if (!rows[0]) throw new Error("V2 workspace 初始化后仍不可读取。"); return { workspaceId: rows[0].workspace_id, data: assertDataShape(rows[0].data), revision: Number(rows[0].revision), createdAt: rows[0].created_at, updatedAt: rows[0].updated_at }; }
export async function saveV2(expectedRevision, data) { const url = getDatabaseUrl(); if (!url) throw new Error("服务端未设置 V2 Neon 连接变量。"); const sql = neon(url); await ensureV2Table(sql); const normalized = assertDataShape(data); const rows = await sql`UPDATE qingxi_app_v2 SET data = \${JSON.stringify(normalized)}::jsonb, revision = revision + 1, updated_at = NOW() WHERE workspace_id = \${WORKSPACE_ID} AND revision = \${Number(expectedRevision)} RETURNING workspace_id, data, revision, created_at, updated_at`; if (!rows[0]) { const current = await loadOrSeedV2(); const error = new Error("revision 冲突，请先刷新后再保存。"); error.code = "REVISION_CONFLICT"; error.current = current; throw error; } return { workspaceId: rows[0].workspace_id, data: assertDataShape(rows[0].data), revision: Number(rows[0].revision), createdAt: rows[0].created_at, updatedAt: rows[0].updated_at }; }

